require 'spec_helper'
require 'json'

# Unit tests for Ducksms::CreditApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CreditApi' do
  before do
    # run before each test
    @api_instance = Ducksms::CreditApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CreditApi' do
    it 'should create an instance of CreditApi' do
      expect(@api_instance).to be_instance_of(Ducksms::CreditApi)
    end
  end

  # unit tests for credit_balance
  # Credit Balance
  # Get available credit balance
  # @param [Hash] opts the optional parameters
  # @return [CreditBalance]
  describe 'credit_balance test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for credit_history
  # Credit History
  # Get all credit history
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [String] :filter_type Filter by credit type
  # @option opts [Integer] :filter_sms_smsid Filter by sms id
  # @return [CreditHistory]
  describe 'credit_history test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
