require 'spec_helper'
require 'json'

# Unit tests for Ducksms::SenderIDApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SenderIDApi' do
  before do
    # run before each test
    @api_instance = Ducksms::SenderIDApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SenderIDApi' do
    it 'should create an instance of SenderIDApi' do
      expect(@api_instance).to be_instance_of(Ducksms::SenderIDApi)
    end
  end

  # unit tests for create_sender
  # Create a Sender ID
  # Create a new sender id
  # @param [Hash] opts the optional parameters
  # @option opts [Sender] :sender Create a new sender
  # @return [CreatedSender]
  describe 'create_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for delete_sender
  # Delete a Sender ID
  # Delete an existing sender id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [DeletedSender]
  describe 'delete_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sender
  # Get a single Sender ID
  # Get details on a single sender id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [GetSender]
  describe 'get_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_sender
  # List Sender ID
  # List all the senders
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [String] :filter_name Filter by sender name
  # @option opts [String] :filter_status Filter by sender status
  # @return [ListSender]
  describe 'list_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_sender
  # Update a Sender ID
  # Update an existing sender id
  # @param id 
  # @param [Hash] opts the optional parameters
  # @option opts [Sender] :sender Update an existing sender id
  # @return [UpdatedSender]
  describe 'update_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
