require 'spec_helper'
require 'json'

# Unit tests for Ducksms::SmsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SmsApi' do
  before do
    # run before each test
    @api_instance = Ducksms::SmsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SmsApi' do
    it 'should create an instance of SmsApi' do
      expect(@api_instance).to be_instance_of(Ducksms::SmsApi)
    end
  end

  # unit tests for sms_send
  # Send Sms
  # Create a new sms
  # @param [Hash] opts the optional parameters
  # @option opts [SmsSchema] :sms_schema Create a new sms
  # @return [PreviewSmsSend]
  describe 'sms_send test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
