require 'spec_helper'
require 'json'

# Unit tests for Ducksms::SmsScheduleApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SmsScheduleApi' do
  before do
    # run before each test
    @api_instance = Ducksms::SmsScheduleApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SmsScheduleApi' do
    it 'should create an instance of SmsScheduleApi' do
      expect(@api_instance).to be_instance_of(Ducksms::SmsScheduleApi)
    end
  end

  # unit tests for cancel_sms_schedule
  # Cancel Sms Schedule
  # Cancel existing sms schedule
  # @param id 
  # @param [Hash] opts the optional parameters
  # @return [CancelSmsSchedule]
  describe 'cancel_sms_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for list_sms_schedule
  # List Sms Schedule
  # List all the sms schedule
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page Page number
  # @option opts [String] :filter_sender_name Filter by sender id name
  # @option opts [String] :filter_type Filter by sms type
  # @option opts [String] :filter_message_type Filter by sms message type
  # @option opts [String] :filter_status Filter by sms status
  # @return [ListSmsSchedule]
  describe 'list_sms_schedule test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
