require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Ducksms::DeletedSender
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DeletedSender' do
  before do
    # run before each test
    @instance = Ducksms::DeletedSender.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DeletedSender' do
    it 'should create an instance of DeletedSender' do
      expect(@instance).to be_instance_of(Ducksms::DeletedSender)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
