require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Ducksms::SmsSchema
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SmsSchema' do
  before do
    # run before each test
    @instance = Ducksms::SmsSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SmsSchema' do
    it 'should create an instance of SmsSchema' do
      expect(@instance).to be_instance_of(Ducksms::SmsSchema)
    end
  end
  describe 'test attribute "preview"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["yes", "no"])
      # validator.allowable_values.each do |value|
      #   expect { @instance.preview = value }.not_to raise_error
      # end
    end
  end

  describe 'test attribute "mobile_numbers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "sender_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "scheduled_at"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "callback_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
