require 'spec_helper'
require 'json'
require 'date'

# Unit tests for Ducksms::UpdatedSender
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'UpdatedSender' do
  before do
    # run before each test
    @instance = Ducksms::UpdatedSender.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of UpdatedSender' do
    it 'should create an instance of UpdatedSender' do
      expect(@instance).to be_instance_of(Ducksms::UpdatedSender)
    end
  end
  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "message"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "data"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
